### ISSUE TITLE
target_mapping : ec2 tag array functionality

### ISSUE THREAD

**Issue by xandrellas** [puppetlabs/puppetlabs-aws_inventory#8]
## Use Case
I'd like to have the EC2 tag of Name be the target of the target_mapping name: clause.
Currently, it appears that array-based results are not query/resolvable outside of filters. 

## Describe the Solution You Would Like
My use case would be to utilize the EC2 tag of Name, which is registered in our DNS, utilized as the targeting mechanism for dynamically generated inventories in AWS.

## Describe Alternatives You've Considered
I am able to target using private_ip_address (an ec2 attribute, per https://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Instance.html), but it does not provide a relatable ease for appropriate users who would run Puppet Bolt against generated inventories.

**Comment by lucywyman** [comment]
Closed by #9
